In [1]:
from sklearn.datasets import load_digits
import numpy as np

ld=load_digits()
ld.target



array([0, 1, 2, ..., 8, 9, 8])

In [2]:
ld.target.shape

(1797,)

In [3]:
ld.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [4]:
ld.data.shape

(1797, 64)

In [5]:
y=(ld.target==9)
y

array([False, False, False, ..., False,  True, False])

In [6]:

a, b = np.unique(y, return_counts=True)
a


array([False,  True])

In [7]:
b

array([1617,  180])

In [8]:
from sklearn.model_selection import train_test_split as tts
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = tts(ld.data,y,stratify=y, random_state=33)
logreg = LogisticRegression(max_iter=10000)
logreg.fit(X_train,y_train)
score=logreg.score(X_test,y_test)
score


0.9888888888888889

In [9]:
pl=logreg.predict(X_test)


In [10]:
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_test, pl) 
confusion

array([[402,   3],
       [  2,  43]])

In [11]:
y_test.shape

(450,)

In [12]:
a, b = np.unique(y_test, return_counts=True)
a

array([False,  True])

In [13]:
b

array([405,  45])

In [14]:
from sklearn.metrics import precision_score
precision=precision_score(y_test, pl)
precision

0.9347826086956522

In [15]:
from sklearn.metrics import recall_score
recall=recall_score(y_test, pl)
recall

0.9555555555555556

In [16]:
from sklearn.metrics import f1_score
f1=f1_score(y_test, pl)
f1

0.945054945054945

In [17]:
from sklearn.metrics import classification_report
cr=classification_report(y_test, pl)
print(cr)

              precision    recall  f1-score   support

       False       1.00      0.99      0.99       405
        True       0.93      0.96      0.95        45

    accuracy                           0.99       450
   macro avg       0.96      0.97      0.97       450
weighted avg       0.99      0.99      0.99       450



In [18]:
df=logreg.decision_function(X_test)


In [19]:
df.shape

(450,)

In [20]:
from sklearn.metrics import precision_recall_curve
precision, recall, thresholds = precision_recall_curve(y_test,df)


In [21]:
precision

array([0.8490566 , 0.84615385, 0.8627451 , 0.88      , 0.87755102,
       0.89583333, 0.91489362, 0.93478261, 0.93333333, 0.95454545,
       0.95348837, 0.95238095, 0.95121951, 0.975     , 0.97435897,
       0.97368421, 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        ])

In [22]:
recall

array([1.        , 0.97777778, 0.97777778, 0.97777778, 0.95555556,
       0.95555556, 0.95555556, 0.95555556, 0.93333333, 0.93333333,
       0.91111111, 0.88888889, 0.86666667, 0.86666667, 0.84444444,
       0.82222222, 0.82222222, 0.8       , 0.77777778, 0.75555556,
       0.73333333, 0.71111111, 0.68888889, 0.66666667, 0.64444444,
       0.62222222, 0.6       , 0.57777778, 0.55555556, 0.53333333,
       0.51111111, 0.48888889, 0.46666667, 0.44444444, 0.42222222,
       0.4       , 0.37777778, 0.35555556, 0.33333333, 0.31111111,
       0.28888889, 0.26666667, 0.24444444, 0.22222222, 0.2       ,
       0.17777778, 0.15555556, 0.13333333, 0.11111111, 0.08888889,
       0.06666667, 0.04444444, 0.02222222, 0.        ])

In [23]:
recall.shape

(54,)

In [24]:
thresholds

array([-1.46054228, -1.11150599, -1.09914424, -0.40802518, -0.29790471,
       -0.29370332, -0.10542644,  0.81878473,  1.8622498 ,  2.11336374,
        2.24217851,  3.09893582,  3.84311105,  4.20988735,  5.20334634,
        5.21207252,  5.28748656,  5.31817529,  7.00227663,  7.17318599,
        8.26506294,  8.78991418,  8.86722316,  9.09861906,  9.20407012,
        9.54776026,  9.71923871,  9.94775122,  9.9663767 , 10.20172287,
       10.26612454, 10.93103604, 11.05853509, 11.4229696 , 11.76661243,
       12.23493747, 13.04477524, 13.24902256, 13.64491376, 13.85529074,
       13.99079276, 14.32721731, 15.08174965, 15.38808528, 15.81383957,
       15.99704763, 16.01976294, 16.31604611, 16.64519042, 17.047477  ,
       17.87809102, 18.1775495 , 18.22823114])

In [25]:
thresholds.shape

(53,)

In [26]:
import matplotlib.pyplot as plt
plt.plot(precision, recall)
plt.xlabel("Precision")
plt.ylabel("Recall")

Text(0, 0.5, 'Recall')

In [27]:
from sklearn.metrics import average_precision_score
aps= average_precision_score(y_test,df)
aps

0.98830251035217

In [28]:
from sklearn.metrics import roc_curve
fpr, tpr, thresholds= roc_curve(y_test,df)

In [29]:
fpr

array([0.        , 0.        , 0.        , 0.00246914, 0.00246914,
       0.00493827, 0.00493827, 0.00740741, 0.00740741, 0.01481481,
       0.01481481, 0.01975309, 0.01975309, 1.        ])

In [30]:
fpr.shape

(14,)

In [31]:
tpr

array([0.        , 0.02222222, 0.82222222, 0.82222222, 0.86666667,
       0.86666667, 0.93333333, 0.93333333, 0.95555556, 0.95555556,
       0.97777778, 0.97777778, 1.        , 1.        ])

In [32]:
tpr.shape

(14,)

In [33]:
thresholds.shape

(14,)

In [34]:
plt.plot(fpr, tpr)
plt.xlabel("fpr")
plt.ylabel("tpr")

Text(0, 0.5, 'tpr')

In [35]:
from sklearn.metrics import roc_auc_score
auc = roc_auc_score(y_test, df)
auc

0.9986282578875172

In [36]:
pp=logreg.predict_proba(X_test)


In [37]:
pp.shape

(450, 2)

In [39]:
pp[:,1].shape

(450,)

In [40]:
fpr, tpr, thresholds= roc_curve(y_test,pp[:,1])
plt.plot(fpr, tpr)
plt.xlabel("fpr")
plt.ylabel("tpr")

Text(0, 0.5, 'tpr')

In [41]:
auc = roc_auc_score(y_test,pp[:,1])
auc

0.9986282578875172